"""
Nginx handler — privileged operations executed by the root agent.

All subprocess execution is delegated to utils.exec.run_command().
No asyncio.create_subprocess_exec() calls exist here.

SSL provisioning flow (create_domain)
──────────────────────────────────────
Phase 1 (always):
  1. Validate domain (defense-in-depth)
  2. Create webroot + default index.html
  3. Render HTTP-only nginx config
  4. Write config, nginx -t, reload          ← domain live via HTTP

Phase 2 (best-effort — never breaks domain creation):
  5. DNS resolution check (skip SSL if domain doesn't resolve)
  6. Validate domain again before cert request
  7. Call ssl.provision_cert() — certbot --webroot
  8. Verify cert files exist on disk
  9. Render HTTPS config (HTTP→HTTPS redirect + TLS server block)
 10. Write HTTPS config, nginx -t
     • on -t failure → roll back to HTTP config, reload, ssl_enabled=False
     • on -t success → reload, ssl_enabled=True
"""
import asyncio
import logging
import os
import re
import socket
from pathlib import Path
from string import Template

from utils.exec import run_command, CommandError

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────

VHOST_DIR      = Path("/etc/nginx/conf.d")
WEBROOT_BASE   = Path("/var/www")
_TEMPLATE_DIR  = Path("/opt/oosoft-securepanel/nginx/templates")
TEMPLATE_FILE  = _TEMPLATE_DIR / "domain.conf.j2"         # HTTP-only
_SSL_TEMPLATE  = _TEMPLATE_DIR / "domain-ssl.conf.j2"     # HTTPS

_LE_LIVE_DIR   = Path("/etc/letsencrypt/live")
_ACME_WEBROOT  = "/var/www/letsencrypt"
_SSL_SNIPPET   = "/etc/nginx/snippets/ssl-params.conf"

# ─────────────────────────────────────────────────────────────────────────────
# Inline fallback templates (string.Template — safe_substitute only)
#
# Escape rules:
#   $domain / ${domain}  →  substituted with the actual domain string
#   $$variable           →  written as $variable in the output file
#                           (nginx variables: $$host, $$uri, $$request_uri …)
#   \\.                  →  Python literal \.  (nginx regex character class)
# ─────────────────────────────────────────────────────────────────────────────

# Phase 1: HTTP-only (ACME challenge served, content delivered over HTTP)
_INLINE_TEMPLATE_HTTP = """\
# /etc/nginx/conf.d/$domain.conf  —  HTTP (auto-generated by Oosoft SecurePanel)
server {
    listen      80;
    listen      [::]:80;
    server_name $domain www.$domain;

    root  /var/www/$domain;
    index index.html index.htm;

    access_log /var/log/nginx/${domain}_access.log combined;
    error_log  /var/log/nginx/${domain}_error.log warn;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location ~ /\\. { deny all; return 404; }
    location ~* (\\.env|wp-config\\.php|\\.git) { deny all; return 404; }

    location / { try_files $$uri $$uri/ =404; }

    # ACME challenge — required for Let's Encrypt initial issuance
    location /.well-known/acme-challenge/ {
        root         /var/www/letsencrypt;
        default_type "text/plain";
        try_files    $$uri =404;
    }

    client_max_body_size 64M;
}
"""

# Phase 2: HTTP redirect + HTTPS server block (deployed after cert issuance)
_INLINE_TEMPLATE_HTTPS = """\
# /etc/nginx/conf.d/$domain.conf  —  HTTPS (auto-generated by Oosoft SecurePanel)

# ── HTTP: ACME passthrough + permanent redirect to HTTPS ──────────────────────
server {
    listen      80;
    listen      [::]:80;
    server_name $domain www.$domain;

    # Keep serving ACME challenges so the cert auto-renews without disruption.
    location /.well-known/acme-challenge/ {
        root         /var/www/letsencrypt;
        default_type "text/plain";
        try_files    $$uri =404;
    }

    # Redirect both apex and www to HTTPS apex (strips www).
    location / {
        return 301 https://$domain$$request_uri;
    }
}

# ── HTTPS ─────────────────────────────────────────────────────────────────────
server {
    listen      443 ssl;
    listen      [::]:443 ssl;
    http2       on;
    server_name $domain;

    # Certificates managed by certbot — renewed automatically.
    ssl_certificate         /etc/letsencrypt/live/$domain/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/$domain/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/$domain/chain.pem;

    # Shared TLS hardening snippet (Mozilla Modern).
    # Installed by ssl-setup.sh to /etc/nginx/snippets/ssl-params.conf
    include /etc/nginx/snippets/ssl-params.conf;

    root  /var/www/$domain;
    index index.html index.htm;

    access_log /var/log/nginx/${domain}_access.log combined;
    error_log  /var/log/nginx/${domain}_error.log warn;

    # Per-domain security headers (ssl-params.conf adds HSTS + others for panel)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location ~ /\\. { deny all; return 404; }
    location ~* (\\.env|wp-config\\.php|\\.git) { deny all; return 404; }

    location / { try_files $$uri $$uri/ =404; }

    client_max_body_size 64M;
}
"""

# ─────────────────────────────────────────────────────────────────────────────
# Internal domain validation (defense-in-depth)
# ─────────────────────────────────────────────────────────────────────────────

_DOMAIN_RE = re.compile(
    r"^(?:[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$"
)


def _assert_safe_domain(domain: str) -> None:
    """
    Second layer of domain validation inside the agent.
    Raises ValueError if the domain is unsafe.  Called at the start of every
    public handler AND again immediately before any certbot invocation.
    """
    if not isinstance(domain, str) or not _DOMAIN_RE.fullmatch(domain):
        raise ValueError(f"Domain failed agent-level validation: {domain!r}")
    if ".." in domain or "/" in domain or "\\" in domain or "\x00" in domain:
        raise ValueError(f"Domain contains forbidden characters: {domain!r}")


def _safe_vhost_path(domain: str) -> Path:
    path = (VHOST_DIR / f"{domain}.conf").resolve()
    if not str(path).startswith(str(VHOST_DIR.resolve()) + "/"):
        raise ValueError("Path traversal detected in vhost path construction")
    return path


def _safe_webroot_path(domain: str) -> Path:
    path = (WEBROOT_BASE / domain).resolve()
    if not str(path).startswith(str(WEBROOT_BASE.resolve()) + "/"):
        raise ValueError("Path traversal detected in webroot path construction")
    return path


# ─────────────────────────────────────────────────────────────────────────────
# Config rendering (no user input reaches string concatenation)
# ─────────────────────────────────────────────────────────────────────────────

def _jinja_env(template_dir: Path):
    """Return a Jinja2 Environment for *template_dir* with autoescape OFF.

    autoescape is disabled because these are nginx config files, not HTML.
    Enabling it would escape double-quotes in add_header directives.
    """
    from jinja2 import Environment, FileSystemLoader
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=False,
        keep_trailing_newline=True,
    )


def _render_config(domain: str) -> str:
    """Render the HTTP-only vhost config for *domain*."""
    if TEMPLATE_FILE.exists():
        try:
            env = _jinja_env(TEMPLATE_FILE.parent)
            return env.get_template(TEMPLATE_FILE.name).render(domain=domain)
        except Exception as exc:
            logger.warning(
                "Jinja2 render failed (%s); using inline HTTP fallback", exc
            )
    return Template(_INLINE_TEMPLATE_HTTP).safe_substitute(domain=domain)


def _render_https_config(domain: str) -> str:
    """Render the HTTPS vhost config (HTTP redirect + TLS block) for *domain*."""
    if _SSL_TEMPLATE.exists():
        try:
            env = _jinja_env(_SSL_TEMPLATE.parent)
            return env.get_template(_SSL_TEMPLATE.name).render(domain=domain)
        except Exception as exc:
            logger.warning(
                "Jinja2 HTTPS render failed (%s); using inline HTTPS fallback", exc
            )
    return Template(_INLINE_TEMPLATE_HTTPS).safe_substitute(domain=domain)


# ─────────────────────────────────────────────────────────────────────────────
# DNS resolution check
# ─────────────────────────────────────────────────────────────────────────────

async def _dns_resolves(domain: str) -> tuple[bool, str | None]:
    """
    Check whether *domain* resolves to at least one A/AAAA record.

    Uses Python's socket.getaddrinfo() via run_in_executor so the event loop
    is not blocked.  No subprocess or external binary needed.

    Returns
    -------
    (True,  first_ip_string)  if the domain resolves.
    (False, None)             if resolution fails or times out.
    """
    loop = asyncio.get_running_loop()
    try:
        # 5-second wall-clock timeout for the DNS query
        results = await asyncio.wait_for(
            loop.run_in_executor(
                None,
                lambda: socket.getaddrinfo(domain, None, proto=socket.IPPROTO_TCP),
            ),
            timeout=5.0,
        )
        if results:
            # results[i] = (family, type, proto, canonname, sockaddr)
            first_ip = results[0][4][0]
            return True, first_ip
        return False, None
    except (socket.gaierror, OSError, asyncio.TimeoutError) as exc:
        logger.debug("DNS check failed for domain=%s: %s", domain, exc)
        return False, None


# ─────────────────────────────────────────────────────────────────────────────
# Nginx primitives — all go through run_command()
# ─────────────────────────────────────────────────────────────────────────────

async def _nginx_test() -> None:
    """
    Run `nginx -t`.  Raises RuntimeError on failure.
    stderr detail is logged by run_command() internally; a generic message
    is raised so callers never forward nginx internals to the network layer.
    """
    try:
        await run_command(["nginx", "-t"])
    except CommandError as exc:
        logger.error("nginx -t failed (rc=%d)", exc.result.returncode)
        raise RuntimeError("Nginx configuration test failed") from exc


async def _nginx_reload() -> None:
    """Reload nginx via systemctl. Raises RuntimeError on failure."""
    try:
        await run_command(["systemctl", "reload", "nginx"])
    except CommandError as exc:
        logger.error("systemctl reload nginx failed (rc=%d)", exc.result.returncode)
        raise RuntimeError("Nginx reload failed") from exc


# ─────────────────────────────────────────────────────────────────────────────
# SSL provisioning helper (called inline — not via agent protocol)
# ─────────────────────────────────────────────────────────────────────────────

async def _provision_ssl(domain: str) -> tuple[bool, str | None]:
    """
    Attempt to obtain a Let's Encrypt certificate and upgrade the vhost config.

    Steps performed:
      a. DNS resolution check — skip SSL if domain doesn't resolve
      b. Domain re-validated (defense-in-depth before cert request)
      c. ssl.provision_cert() — certbot --webroot
      d. Verify cert files on disk
      e. nginx -t with HTTPS config
      f. nginx reload

    This function NEVER raises.  All failures are caught, logged, and returned
    as (False, error_message) so create_domain() can keep the HTTP config live.

    Returns
    -------
    (True,  None)          certificate issued, HTTPS config active
    (False, reason_str)    something failed — HTTP config remains unchanged
    """
    # ── a. DNS check ──────────────────────────────────────────────────────────
    resolves, resolved_ip = await _dns_resolves(domain)
    if not resolves:
        logger.warning(
            "SSL skipped for domain=%s: DNS does not resolve.  "
            "Point an A record at this server and re-run ssl.issue.",
            domain,
        )
        return False, "DNS does not resolve for domain — SSL skipped"

    logger.info("DNS OK for domain=%s resolved_ip=%s", domain, resolved_ip)

    # ── b. Re-validate domain before touching certbot ─────────────────────────
    try:
        _assert_safe_domain(domain)
    except ValueError as exc:
        logger.error("Domain re-validation failed before SSL request: %s", exc)
        return False, "Domain validation failed before SSL request"

    # ── c. Issue certificate ──────────────────────────────────────────────────
    # Import here (not at module top) to avoid circular imports between
    # handlers.nginx ↔ handlers.ssl.
    try:
        from handlers.ssl import provision_cert
        admin_email = os.environ.get("PANEL_ADMIN_EMAIL", "ssl-admin@localhost")
        await provision_cert(domain, _ACME_WEBROOT, email=admin_email)
    except RuntimeError as exc:
        logger.error(
            "SSL provisioning failed for domain=%s — keeping HTTP config: %s",
            domain, exc,
        )
        return False, "SSL certificate issuance failed"
    except Exception as exc:
        logger.exception(
            "Unexpected error during SSL provisioning for domain=%s", domain
        )
        return False, "Unexpected error during SSL provisioning"

    # ── d. Sanity-check cert files ────────────────────────────────────────────
    cert_dir = _LE_LIVE_DIR / domain
    for fname in ("fullchain.pem", "privkey.pem", "chain.pem"):
        if not (cert_dir / fname).exists():
            logger.error(
                "Cert file missing after issuance: %s/%s", cert_dir, fname
            )
            return (
                False,
                f"Certificate file {fname} missing after issuance",
            )

    # ── e–f. Deploy HTTPS config ──────────────────────────────────────────────
    # The return value (config content written) is not used here; the caller
    # is responsible for storing the current HTTP config for rollback.
    return True, None


# ─────────────────────────────────────────────────────────────────────────────
# Public handlers
# ─────────────────────────────────────────────────────────────────────────────

async def reload(params: dict) -> dict:
    """Test nginx config then reload.  Kept for existing callers."""
    await _nginx_test()
    await _nginx_reload()
    return {"reloaded": True}


async def create_domain(params: dict) -> dict:
    """
    Provision a new domain — HTTP first, then best-effort HTTPS upgrade.

    Phase 1 (always, hard-fails on error):
      1. Validate domain (defense-in-depth)
      2. Create webroot + default index.html
      3. Render HTTP-only nginx config
      4. Write config, nginx -t (rollback on failure), reload

    Phase 2 (best-effort — SSL failure never breaks domain creation):
      5. DNS check
      6. Domain re-validated before certbot
      7. certbot --webroot (via ssl.provision_cert)
      8. Cert-file existence check
      9. Render HTTPS config, write, nginx -t
         • -t failure → rollback to HTTP config, keep domain live via HTTP
         • -t success → reload, domain live via HTTPS

    Response fields
    ───────────────
    webroot     : absolute path to the document root
    config      : absolute path to the active nginx vhost config
    domain      : domain name (lowercased, normalised)
    ssl_enabled : True if HTTPS was successfully provisioned
    ssl_error   : human-readable reason if ssl_enabled is False (or None)
    """
    domain = params["domain"]
    _assert_safe_domain(domain)

    webroot    = _safe_webroot_path(domain)
    vhost_path = _safe_vhost_path(domain)

    # ── 1. Webroot ─────────────────────────────────────────────────────────────
    webroot.mkdir(parents=True, exist_ok=True)
    webroot.chmod(0o755)

    # ── 2. Default index.html ─────────────────────────────────────────────────
    index_file = webroot / "index.html"
    if not index_file.exists():
        index_file.write_text(
            f"<!DOCTYPE html>\n<html lang='en'>\n"
            f"<head><meta charset='UTF-8'>"
            f"<title>Welcome to {domain}</title></head>\n"
            f"<body><h1>{domain} is live.</h1>"
            f"<p>Hosted on Oosoft SecurePanel.</p></body>\n</html>\n",
            encoding="utf-8",
        )
        index_file.chmod(0o644)
        logger.info("Created index.html for domain=%s", domain)

    # ── 3. Render HTTP-only config ─────────────────────────────────────────────
    http_config = _render_config(domain)

    # ── 4. Write config + test + reload ───────────────────────────────────────
    vhost_path.write_text(http_config, encoding="utf-8")
    vhost_path.chmod(0o644)
    logger.info("Wrote HTTP nginx config: %s", vhost_path)

    try:
        await _nginx_test()
    except RuntimeError:
        vhost_path.unlink(missing_ok=True)
        logger.error("Rolled back nginx config for domain=%s", domain)
        raise   # hard-fail — domain was never reachable

    await _nginx_reload()
    logger.info("Domain live via HTTP: domain=%s webroot=%s", domain, webroot)

    # ── Phase 2: best-effort SSL ───────────────────────────────────────────────
    ssl_enabled = False
    ssl_error: str | None = None

    # Check ssl-params.conf snippet exists; warn early rather than discovering
    # it only after certbot completes successfully.
    if not Path(_SSL_SNIPPET).exists():
        ssl_error = (
            f"SSL snippet not found at {_SSL_SNIPPET}. "
            "Run ssl-setup.sh to install it, then issue the cert manually."
        )
        logger.warning(
            "ssl-params.conf missing — SSL provisioning skipped for domain=%s. %s",
            domain, ssl_error,
        )
    else:
        # ── 5–8. Attempt cert issuance ─────────────────────────────────────────
        cert_ok, cert_err = await _provision_ssl(domain)

        if not cert_ok:
            ssl_error = cert_err
            # HTTP config is already active — nothing else to do.
        else:
            # ── 9. Render HTTPS config ─────────────────────────────────────────
            https_config = _render_https_config(domain)

            # Write the HTTPS config, replacing the HTTP-only version.
            vhost_path.write_text(https_config, encoding="utf-8")
            vhost_path.chmod(0o644)
            logger.info("Wrote HTTPS nginx config: %s", vhost_path)

            try:
                await _nginx_test()
            except RuntimeError as exc:
                # ── Rollback to HTTP config ────────────────────────────────────
                logger.error(
                    "HTTPS nginx config failed for domain=%s — rolling back: %s",
                    domain, exc,
                )
                ssl_error = "HTTPS nginx config test failed after cert issuance"

                # Restore the known-good HTTP config.
                vhost_path.write_text(http_config, encoding="utf-8")
                try:
                    await _nginx_test()
                    await _nginx_reload()
                    logger.info(
                        "HTTP rollback succeeded for domain=%s", domain
                    )
                except RuntimeError:
                    # Extremely unlikely: HTTP config that passed earlier now
                    # fails.  Log at CRITICAL — human intervention needed.
                    logger.critical(
                        "HTTP rollback ALSO FAILED for domain=%s — "
                        "nginx may be in a broken state!",
                        domain,
                    )
            else:
                # HTTPS config is valid — reload and mark success.
                await _nginx_reload()
                ssl_enabled = True
                logger.info(
                    "HTTPS active for domain=%s cert_dir=%s",
                    domain, _LE_LIVE_DIR / domain,
                )

    result = {
        "domain":      domain,
        "webroot":     str(webroot),
        "config":      str(vhost_path),
        "ssl_enabled": ssl_enabled,
        "ssl_error":   ssl_error,
    }
    logger.info("create_domain complete: %s", result)
    return result


async def delete_domain(params: dict) -> dict:
    """Remove a domain's nginx config; remove webroot only if empty."""
    domain = params["domain"]
    _assert_safe_domain(domain)

    vhost_path = _safe_vhost_path(domain)
    webroot    = _safe_webroot_path(domain)

    config_removed = webroot_removed = False

    if vhost_path.exists():
        vhost_path.unlink()
        config_removed = True
        logger.info("Removed nginx config: %s", vhost_path)

    if config_removed:
        try:
            await _nginx_test()
            await _nginx_reload()
        except RuntimeError as exc:
            logger.error(
                "Nginx reload failed after deleting domain=%s: %s", domain, exc
            )
            raise

    if webroot.exists() and not any(webroot.iterdir()):
        webroot.rmdir()
        webroot_removed = True
        logger.info("Removed empty webroot: %s", webroot)

    return {
        "domain":         domain,
        "config_removed": config_removed,
        "webroot_removed": webroot_removed,
    }


async def write_vhost(params: dict) -> dict:
    """Write a pre-rendered vhost config (PHP/SSL flow)."""
    username = params["username"]
    domain   = params["domain"]
    config   = params["config_content"]

    _assert_safe_domain(domain)

    vhost_file = (VHOST_DIR / f"{username}_{domain}.conf").resolve()
    if not str(vhost_file).startswith(str(VHOST_DIR.resolve()) + "/"):
        raise ValueError("Path traversal detected in write_vhost")

    vhost_file.write_text(config, encoding="utf-8")
    vhost_file.chmod(0o644)
    return {"file": str(vhost_file)}


async def delete_vhost(params: dict) -> dict:
    """Remove a user-namespaced vhost config."""
    username = params["username"]
    domain   = params["domain"]

    _assert_safe_domain(domain)

    vhost_file = (VHOST_DIR / f"{username}_{domain}.conf").resolve()
    if not str(vhost_file).startswith(str(VHOST_DIR.resolve()) + "/"):
        raise ValueError("Path traversal detected in delete_vhost")

    if vhost_file.exists():
        vhost_file.unlink()
    return {"deleted": True}
